name: CI/CD Pipeline
on:
  push:
    branches: 
      - "**"
env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/weather_planner_app
jobs:
  #1) Test Job
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
  
      - name: Run Tests
        run: pytest
        
  #2) Build and Push to Docker Hub
  build:
    runs-on: ubuntu-latest
    needs: test
    environment: devtest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:latest .
  
      - name: Push Image to Docker Hub
        run: docker push ${{ env.DOCKER_IMAGE }}:latest
        
  #3) Deploy to AWS
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy Image
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.AWS_ADDRESS }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PEM }}
          script: |
            docker pull ${{ env.DOCKER_IMAGE }}:latest
            docker stop weather_planner_app || true
            docker rm weather_planner_app || true
            docker run -d -e DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }} -p 8000:8000 --name weather_planner_app ${{ env.DOCKER_IMAGE }}:latest