name: CI/CD Pipeline

on:
  push:
    branches: [  "main"  ]
env:
  DOCKER_IMAGE: ${{  secrets.DOCKER_HUB_USERNAME }}/weather_planner_app

jobs:

#1) Test Job
test:
  runs_on: ubuntu-latest

  steps:
    - name: Checkout Repository
      uses: actions/Checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run Tests
      run: pytest
      
#2) Build and Push to Docker Hub
build:
  runs-on: ubuntu-latest
  needs: test

  steps:
    - name: Checkout Repository
      uses: actions/Checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{  secrets.DOCKER_HUB_USERNAME  }}
        password: ${{  secrets.DOCKER_HUB_ACCESS_TOKEN  }}

    - name: Build Docker Image
      run: docker build -t $DOCKER_IMAGE .

    - name: Push Image to Docker Hub
      run: docker push $DOCKER_IMAGE
      
